# -*- coding:Utf-8 -*-
# Code Utf-8 qui permet de conserver les caractères saisis.
##------------------------------------------------------------------------------
from tkinter import *
from tkinter.messagebox import *
from tkinter.filedialog import *
from random import sample
# Importation des différents modules utilisés dans le programme.
##------------------------------------------------------------------------------
class Principale():
# La classe Principale qui permet d'ouvrir la fenetre principale.
##------------------------------------------------------------------------------
    def __init__(self):
        self.fen=Tk()
        self.fen.resizable(0,0)
        self.fen.title("Service INP.GERMINATOR")
        self.fen.config(bg="light green")
        photo2=PhotoImage(file="ban1.gif")
        frameH = Frame(self.fen, relief=GROOVE, bd=3)
        frameH.pack( pady=3)
        canvas=Canvas(frameH,width=photo2.width(),height=photo2.height())
        canvas.create_image(0,0,anchor=NW,image=photo2)
        canvas.pack(side=TOP)
        label=LabelFrame(self.fen,text="Bienvenue au GerminatorService dédié aux élèves de l'INP-HB.",font="ComicSansMS 12 bold",padx=10,pady=10,bg="cyan")
        label.pack(fill="both",expand="yes")
        Label(label,text="Ce service fait l'enregistrement des élèves résident au sein de l'INP-HB dans un fichier, permettant\nainsi de connaitre le nombre d'élèves et de pouvoir les identifier au moment opportun. Si vous en\nfaites partir veuillez-vous inscrire, pour se faire cliquer sur le bouton Enregistrer.",font="Verdana 13 bold",fg="black",bg="cyan").pack()
        frameB = Frame(self.fen, relief=GROOVE, bd=3)
        frameB.pack( pady=3)
        self.b1 = Button( frameB,text="Enregistrer",underline=0,font="Verdana 12 bold",bg="orange",fg="black",padx=20,pady=5,command=self.enregistrer)
        b2 = Button( frameB,text="Quitter",underline=0,font="Verdana 12 bold",bg="white",fg="black",command=self.fen.destroy,padx=20,pady=5)
        self.b3 = Button( frameB,text="Consulter",underline=0,font="Verdana 12 bold",bg="green",fg="black",padx=20,pady=5,command=self.consulter)
        self.b1.pack( side=LEFT, pady=2)
        b2.pack( side=LEFT, pady=2)
        self.b3.pack( side=LEFT, pady=2)
        photo=PhotoImage(file="inp-centre.gif")
        canvas=Canvas(label,width=photo.width(),height=photo.height(),bg="cyan")
        canvas.create_image(0,0,anchor=NW,image=photo)
        canvas.pack()
        photo1=PhotoImage(file="nav_bg.gif")
        canvas=Canvas(self.fen,width=photo1.width(),height=photo1.height())
        canvas.create_image(0,0,anchor=NW,image=photo1)
        canvas.pack()
        label1=Label(self.fen,text="Copyright © 2016-2017 - ServiceInpGerminator.ci - Tous droits réservés - Tél : 49 01 29 66 / 40 45 90 45 - Email : inp@germinatorservice.net  *********  G€rmin@t¤rPr¤dµcti¤n",anchor=CENTER,bg="light green",fg="black",font="bold 10")
        label1.pack()
        self.fen.mainloop()
##------------------------------------------------------------------------------
class Enregistrer(Principale):
# La classe Enregistrer qui permet d'ouvrir la fenetre Enregestrer apres appui sur le boutton Enregistrer de la fenetre principale.
##------------------------------------------------------------------------------
    def enregistrer(self):
        self.fen.destroy()
        self.fen1 = Tk()
        self.fen1.resizable(0,0)
        self.fen1.title("Enregistrement")
        self.fen1.config( relief=RAISED, bd=3,bg="light green")
        frameH = Frame(self.fen1, relief=GROOVE, bd=2,bg="orange")
        frameH.pack()
        frameH1=Frame(frameH, relief=GROOVE, bd=2,bg="cyan")
        frameH1.pack(side=LEFT)
        label=LabelFrame(frameH1,text="Nous vous prions de bien vouloir remplir ce formulaire ci dessous !",font="Verdana 15 bold",padx=10,pady=10,bg="cyan")
        label.pack(fill="both",expand="yes")
        Label(label, text="Noms :",font="Verdana 15 bold",bg="cyan").grid( row=0, column=0, sticky=W,padx=10)
        self.nameEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.nameEnt.insert(1,"Ex: AGBETOGOR")
        self.nameEnt.grid( row=0, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Prénoms :",font="Verdana 15 bold",bg="cyan" ).grid( row=1, column=0, sticky=W,padx=10)
        self.prenameEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.prenameEnt.insert(1,"Ex: KOKOU DZODZI GERMAIN")
        self.prenameEnt.grid( row=1, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Date de naissance :",font="Verdana 15 bold",bg="cyan" ).grid( row=2, column=0, sticky=W,padx=10)
        self.dateEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.dateEnt.insert(1,"Ex: 28-05-1997")
        self.dateEnt.grid( row=2, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Lieu de naissance :",font="Verdana 15 bold",bg="cyan" ).grid( row=3, column=0, sticky=W,padx=10)
        self.lieuEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.lieuEnt.insert(1,"Ex: PORT-BOUET")
        self.lieuEnt.grid( row=3, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="N° Carte Etudiant :",font="Verdana 15 bold",bg="cyan" ).grid( row=4, column=0, sticky=W,padx=10)
        self.carteEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.carteEnt.insert(1,"Ex: 14INP00631")
        self.carteEnt.grid( row=4, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Site :",font="Verdana 15 bold",bg="cyan" ).grid( row=5, column=0, sticky=W,padx=10)
        self.site=StringVar()
        self.site.set("INP CENTRE")
        option=OptionMenu(label,self.site,"INP CENTRE","   INP  SUD   ")
        option.grid(row=5, column=1, sticky=W, padx=20, pady=7,ipadx=129)
        Label(label, text="Résidence-Chambre :",font="Verdana 15 bold",bg="cyan" ).grid( row=6, column=0, sticky=W,padx=10)
        self.rchEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.rchEnt.insert(1,"Ex: R-35")
        self.rchEnt.grid( row=6, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="N° Téléphone :",font="Verdana 15 bold",bg="cyan").grid( row=7, column=0, sticky=W,padx=10)
        self.phoneEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.phoneEnt.insert(1,"Ex: 49 01 29 66")
        self.phoneEnt.grid( row=7, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="E-mail :",font="Verdana 15 bold",bg="cyan" ).grid( row=8, column=0, sticky=W,padx=10)
        self.mailEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.mailEnt.insert(1,"Ex: agbegermain@gmail.com")
        self.mailEnt.grid( row=8, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Ecole :",font="Verdana 15 bold",bg="cyan").grid( row=9, column=0, sticky=W,padx=10)
        self.ecole=StringVar()
        self.ecole.set("ESCAE")
        option=OptionMenu(label,self.ecole,"   ESI   ","   ESA  ","  ESTP "," ESMG","ESCAE","    EP   ")
        option.grid(row=9, column=1, sticky=W, padx=20, pady=7,ipadx=144)
        Label( label, text="Filière :",font="Verdana 15 bold",bg="cyan").grid( row=10, column=0, sticky=W,padx=10)
        self.filiereEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.filiereEnt.insert(1,"Ex: ING STIC1")
        self.filiereEnt.grid( row=10, column=1, sticky=W, padx=20, pady=7)
        Label(label,text="Sexe :",font="Verdana 15 bold",bg="cyan").grid( row=11, column=0, sticky=W,padx=10)
        self.sexe=StringVar()
        boutton1=Radiobutton(label,text="Masculin",font="TimesNewRoman 13 bold",bg="cyan",value="Masculin",variable=self.sexe)
        boutton1.grid( row=11, column=1, sticky=W, padx=20, pady=7)
        boutton2=Radiobutton(label,text="Féminin",font="TimesNewRoman 13 bold",bg="cyan",value="Féminin",variable=self.sexe)
        boutton2.grid( row=11, column=1, sticky=W, padx=130, pady=7)
        frameH2=Frame(frameH,bg="orange")
        frameH2.pack(side=RIGHT)
        photo = PhotoImage(file ='251180logo_inp.gif' )
        can1 = Canvas(frameH2, width =photo.width(), height =photo.height(),bg="orange")
        can1.create_image(0,0,anchor=NW,image =photo)
        can1.pack()
        frameM = Frame(self.fen1,relief=GROOVE, bd=2,bg="red",padx=10,pady=5)
        frameM.pack()
        frameB = Frame(self.fen1, relief=GROOVE, bd=3)
        frameB.pack(side=BOTTOM,pady=3)
        b1 = Button(frameB,text="Envoyer",underline=0,font="Verdana 12 bold",bg="orange",fg="black",padx=20,pady=5,command=self.envoyer)
        b2 = Button(frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="green",fg="black",padx=20,pady=5,command=self.retour)
        b1.pack( side=LEFT, pady=2)
        b2.pack( side=LEFT, pady=2)
        self.fen1.mainloop()
##------------------------------------------------------------------------------
class Consulter(Enregistrer):
# La classe Consulter qui permet d'ouvrir la fenetre Consulter apres appui du boutton Consulter de la fenetre principale.
##------------------------------------------------------------------------------
    def consulter(self):
        self.fen.destroy()
        self.fen2=Tk()
        self.fen2.resizable(0,0)
        self.fen2.title("Consultation")
        self.fen2.config(bg="light green")
        self.frameH = Frame(self.fen2, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
        self.frameH.pack()
        label=LabelFrame(self.frameH,text="Consulter la liste des inscris à ce service, vous donne l'autorisation de voir celle-ci et d'apporter ensuite différentes\nmodifications. Pour se faire cliquer sur le nom auquel vous voudriez apporter des modifications et suivez les instructions.",font="Verdana 15",bg="cyan")
        label.pack(pady=5)
        frameH1 = Frame(label,bg="cyan",padx=20,pady=20)
        frameH1.pack(side=LEFT)
        frameH2 = Frame(label,bg="cyan",padx=20,pady=20)
        frameH2.pack(side=RIGHT)
        frameB = Frame(self.fen2, relief=GROOVE, bd=3)
        frameB.pack( pady=3)
        b2 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.retour1,padx=20,pady=5)
        b2.pack( side=LEFT, pady=2)
        self.liste= Listbox(frameH1,font="Castellar 15 bold")
        sbar=Scrollbar(self.liste,orient=VERTICAL,command=self.liste.yview)
        self.liste.configure(yscrollcommand=sbar.set)
        sbar.pack(side=RIGHT,fill=Y)
        self.liste.pack(side=LEFT,expand=YES,fill=BOTH)
        photo=PhotoImage(file="intelligencia copie.gif")
        canvas=Canvas(frameH2,width=photo.width(),height=photo.height())
        canvas.create_image(0,0,anchor=NW,image=photo)
        canvas.pack()
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        self.choix=StringVar()
        for i in range(len(self.code)):
            self.maliste=self.code[i].split("*²&~#@$§")
            boutton=Radiobutton(self.liste,text=self.maliste[0] + " " + self.maliste[1],variable=self.choix,value=self.maliste[0],font="Castellar 15 bold",command=self.afficher,bg="light green",fg="red")
            boutton.pack(side=TOP,ipady=10,ipadx=10,padx=5,pady=5,fill=BOTH)
        fichier.close()
        if len(self.code)==0:
            showinfo("Information","Le fichier des inscris à ce service est vide !!!")
        self.fen2.mainloop()
##------------------------------------------------------------------------------
class Envoyer(Consulter):
# La classe Envoyer qui permet d'enregistrer l'inscrit dans un fichier texte apres appui sur le boutton Envoyer.
##------------------------------------------------------------------------------
    def __init__( self):
        Enregistrer.enregistrer(self)
##------------------------------------------------------------------------------
    def envoyer( self):
        self.alpha=["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
        self.alpha1=sample(self.alpha,4)
        self.alpha2="17INPHB00"+self.alpha1[0]+self.alpha1[1]+self.alpha1[2]+self.alpha1[3]
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        for i in range(len(self.code)):
            self.maliste=self.code[i].split("*²&~#@$§")
            if self.maliste[4]!=self.alpha2:
                pass
            else:
                self.alpha2="17INPHB00"+self.alpha1[3]+self.alpha1[2]+self.alpha1[1]+self.alpha1[0]
        self.ajout = ["","","","","","","","","","","","",""]
        self.ajout[0] = self.nameEnt.get()
        self.ajout[1] = self.prenameEnt.get()
        self.ajout[2] = self.dateEnt.get()
        self.ajout[3] = self.lieuEnt.get()
        self.ajout[4] = self.alpha2
        self.ajout[5] = self.carteEnt.get()
        self.ajout[6] = self.site.get()
        self.ajout[7] = self.rchEnt.get()
        self.ajout[8] = self.phoneEnt.get()
        self.ajout[9] = self.mailEnt.get()
        self.ajout[10] = self.ecole.get()
        self.ajout[11] = self.filiereEnt.get()
        self.ajout[12] = self.sexe.get()
        if (self.ajout[0]=="") or (self.ajout[1]=="") or (self.ajout[2]=="") or (self.ajout[3]=="") or (self.ajout[5]=="") or (self.ajout[7]=="") or (self.ajout[8]=="") or (self.ajout[9]=="") or (self.ajout[11]=="") or (self.ajout[0]==" ") or (self.ajout[1]==" ") or (self.ajout[2]==" ") or (self.ajout[3]==" ") or (self.ajout[5]==" ") or ( self.ajout[7]==" ") or (self.ajout[8]==" ") or (self.ajout[9]==" ") or (self.ajout[11]==" ") or (self.ajout[0]=="Ex: AGBETOGOR") or (self.ajout[1]=="Ex: KOKOU DZODZI GERMAIN") or (self.ajout[2]=="Ex: 28-05-1997") or (self.ajout[3]=="Ex: PORT-BOUET") or (self.ajout[5]=="Ex: 14INP00631") or (self.ajout[7]=="Ex: R-35") or (self.ajout[8]=="Ex: 49 01 29 66") or (self.ajout[9]=="Ex: agbegermain@gmail.com") or (self.ajout[11]=="Ex: ING STIC1"):
            showwarning("Alarme", "Veuillez renseigner les champs svp !!!")
            return
        elif self.ajout[12]=="":
            showwarning("Alarme", "Veuillez sélectionner un sexe svp !!!")
            return
        self.nameEnt.focus()
        self.prenameEnt.focus()
        self.dateEnt.focus()
        self.lieuEnt.focus()
        self.carteEnt.focus()
        self.rchEnt.focus()
        self.phoneEnt.focus()
        self.mailEnt.focus()
        self.filiereEnt.focus()
        print(self.ajout[4])
        f2=open("Germinator.txt", "a" )
        f2.write( "%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s*²&~#@$§%s\n" % ( self.ajout[0],self.ajout[1],self.ajout[2],self.ajout[3],self.ajout[4],self.ajout[5],self.ajout[6],self.ajout[7],self.ajout[8],self.ajout[9],self.ajout[10],self.ajout[11],self.ajout[12]))
        f2.close()
        if self.ajout[12]=="Masculin":
            showinfo("Information","Monsieur "+self.ajout[0]+" votre inscription est terminée. Votre mot de passe d'accès est le suivant : " +self.ajout[4]+ ".Ceci vous permettra de consulter vos informations ultérieurement. Merci et à bientôt !!!")
        if self.ajout[12]=="Féminin":
            showinfo("Information","Madame "+self.ajout[0]+" votre inscription est terminée. Votre mot de passe d'accès est le suivant : " +self.ajout[4]+ ".Ceci vous permettra de consulter vos informations ultérieurement.  Merci et à bientôt !!!")
        self.fen1.destroy()
        self.fen5=Tk()
        self.fen5.resizable(0,0)
        self.fen5.title("Mes informations")
        self.fen5.config(bg="light green")
        self.frameH = Frame(self.fen5, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
        self.frameH.pack()
        label=LabelFrame(self.frameH,text="Voici vos différentes informations saisies pour votre enregistrement.",font="Verdana 15",bg="cyan")
        label.pack()
        photo = PhotoImage(file ='sablier,-chateau-de-sable-182334.gif' )
        can1 = Canvas(label, width =photo.width(), height =photo.height(),bg="cyan")
        can1.create_image(0,0,anchor=NW,image =photo)
        can1.pack(side=RIGHT)
        frameB = Frame(self.fen5, relief=GROOVE, bd=3)
        frameB.pack( pady=3)
        b2 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.retour4,padx=20,pady=5)
        b2.pack( side=LEFT, pady=2)
        self.liste= Listbox(label,font="Castellar 13 bold",height=25,width=35)
        self.liste.pack(padx=5,pady=5,ipadx=5,ipady=5)
        self.liste.insert(0,"1-Noms : " + self.ajout[0])
        self.liste.insert(1,"")
        self.liste.insert(2,"2-Prénoms : " + self.ajout[1])
        self.liste.insert(3,"")
        self.liste.insert(4,"3-Date de naissance : " + self.ajout[2])
        self.liste.insert(5,"")
        self.liste.insert(6,"4-Lieu de naissance : " + self.ajout[3])
        self.liste.insert(7,"")
        self.liste.insert(9,"5-Mot de passe : " + self.ajout[4])
        self.liste.insert(10,"")
        self.liste.insert(11,"6-N° Carte Etudiant : " + self.ajout[5])
        self.liste.insert(12,"")
        self.liste.insert(13,"7-Site : " + self.ajout[6])
        self.liste.insert(14,"")
        self.liste.insert(15,"8-Résidence-Chambre : " + self.ajout[7])
        self.liste.insert(16,"")
        self.liste.insert(17,"9-Téléphone : " + self.ajout[8])
        self.liste.insert(18,"")
        self.liste.insert(19,"10-E-mail : " + self.ajout[9])
        self.liste.insert(20,"")
        self.liste.insert(21,"11-Ecole : " + self.ajout[10])
        self.liste.insert(22,"")
        self.liste.insert(23,"12-Filière : " + self.ajout[11])
        self.liste.insert(24,"")
        self.liste.insert(25,"13-Sexe : " + self.ajout[12])
        self.fen5.mainloop()
##------------------------------------------------------------------------------
class Boutton(Envoyer):
# La classe Boutton qui permet d'afficher la liste des inscris et de soit modifier, soit supprimer un element.
##-----------------------------------------------------------------------------
    def __init__(self):
        Consulter.consulter(self)
##------------------------------------------------------------------------------
    def afficher(self):
        self.matricule=input("Veuillez saisir votre mot de passe d'accès :")
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        for i in range(len(self.code)):
            self.maliste=self.code[i].split("*²&~#@$§")
            if (self.matricule==self.maliste[4]) and (self.maliste[0]==self.choix.get()):
                self.h=i
                showinfo("Information","Votre mot de passe correspond, vous pouvez donc consulter vos différentes informations !!!")
                self.fen2.destroy()
                self.fen4=Tk()
                self.fen4.resizable(0,0)
                self.fen4.title("Mes informations")
                self.fen4.config(bg="light green")
                frameH = Frame(self.fen4, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
                frameH.pack()
                label=LabelFrame(frameH,text="Vous pouvez en consultant vos informations de soit apporter une quelconque modification\nà vos données, soit de ne plus en faire partir en supprimant vos données.",font="Verdana 15",bg="cyan")
                label.pack()
                photo = PhotoImage(file ='sablier,-chateau-de-sable-182334.gif' )
                can1 = Canvas(label, width =photo.width(), height =photo.height(),bg="cyan")
                can1.create_image(0,0,anchor=NW,image =photo)
                can1.pack(side=RIGHT)
                frameB = Frame(self.fen4, relief=GROOVE, bd=3)
                frameB.pack( pady=3)
                b1 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="orange",fg="black",command=self.retour3,padx=20,pady=5)
                b1.pack( side=LEFT, pady=2)
                b2 = Button( frameB,text="Supprimer",underline=0,font="Verdana 12 bold",bg="white",fg="black",command=self.supprimer,padx=20,pady=5)
                b2.pack( side=LEFT, pady=2)
                b3 = Button( frameB,text="Modifier",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.modifier,padx=20,pady=5)
                b3.pack( side=LEFT, pady=2)
                self.liste= Listbox(label,font="Castellar 13 bold",height=25,width=35)
                self.liste.pack(padx=5,pady=5,ipadx=5,ipady=5)
                self.liste.insert(0,"1-Noms : " + self.maliste[0])
                self.liste.insert(1,"")
                self.liste.insert(2,"2-Prénoms : " + self.maliste[1])
                self.liste.insert(3,"")
                self.liste.insert(4,"3-Date de naissance : " + self.maliste[2])
                self.liste.insert(5,"")
                self.liste.insert(6,"4-Lieu de naissance : " + self.maliste[3])
                self.liste.insert(7,"")
                self.liste.insert(8,"5-Mot de passe : " + self.maliste[4])
                self.liste.insert(9,"")
                self.liste.insert(10,"6-N° Carte Etudiant : " + self.maliste[5])
                self.liste.insert(11,"")
                self.liste.insert(12,"7-Site : " + self.maliste[6])
                self.liste.insert(13,"")
                self.liste.insert(14,"8-Résidence-Chambre : " + self.maliste[7])
                self.liste.insert(15,"")
                self.liste.insert(16,"9-Téléphone : " + self.maliste[8])
                self.liste.insert(17,"")
                self.liste.insert(18,"10-E-mail : " + self.maliste[9])
                self.liste.insert(19,"")
                self.liste.insert(20,"11-Ecole : " + self.maliste[10])
                self.liste.insert(21,"")
                self.liste.insert(22,"12-Filière : " + self.maliste[11])
                self.liste.insert(23,"")
                self.liste.insert(24,"13-Sexe : " + self.maliste[12])
                fichier.close()
                self.fen4.mainloop()
##------------------------------------------------------------------------------
    def afficher1(self):
        self.matricule=input("Veuillez saisir votre mot de passe d'accès :")
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        for i in range(len(self.code)):
            self.maliste=self.code[i].split("*²&~#@$§")
            if (self.matricule==self.maliste[4]) and (self.maliste[0]==self.choix.get()):
                self.h=i
                showinfo("Information","Votre mot de passe correspond, vous pouvez donc consulter vos différentes informations !!!")
                self.fen6.destroy()
                self.fen4=Tk()
                self.fen4.resizable(0,0)
                self.fen4.title("Mes informations")
                self.fen4.config(bg="light green")
                frameH = Frame(self.fen4, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
                frameH.pack()
                label=LabelFrame(frameH,text="Vous pouvez en consultant vos informations de soit apporter une quelconque modification\nà vos données, soit de ne plus en faire partir en supprimant vos données.",font="Verdana 15",bg="cyan")
                label.pack()
                photo = PhotoImage(file ='sablier,-chateau-de-sable-182334.gif' )
                can1 = Canvas(label, width =photo.width(), height =photo.height(),bg="cyan")
                can1.create_image(0,0,anchor=NW,image =photo)
                can1.pack(side=RIGHT)
                frameB = Frame(self.fen4, relief=GROOVE, bd=3)
                frameB.pack( pady=3)
                b1 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="orange",fg="black",command=self.retour3,padx=20,pady=5)
                b1.pack( side=LEFT, pady=2)
                b2 = Button( frameB,text="Supprimer",underline=0,font="Verdana 12 bold",bg="white",fg="black",command=self.supprimer,padx=20,pady=5)
                b2.pack( side=LEFT, pady=2)
                b3 = Button( frameB,text="Modifier",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.modifier,padx=20,pady=5)
                b3.pack( side=LEFT, pady=2)
                self.liste= Listbox(label,font="Castellar 13 bold",height=25,width=35)
                self.liste.pack(padx=5,pady=5,ipadx=5,ipady=5)
                self.liste.insert(0,"1-Noms : " + self.maliste[0])
                self.liste.insert(1,"")
                self.liste.insert(2,"2-Prénoms : " + self.maliste[1])
                self.liste.insert(3,"")
                self.liste.insert(4,"3-Date de naissance : " + self.maliste[2])
                self.liste.insert(5,"")
                self.liste.insert(6,"4-Lieu de naissance : " + self.maliste[3])
                self.liste.insert(7,"")
                self.liste.insert(8,"5-Mot de passe : " + self.maliste[4])
                self.liste.insert(9,"")
                self.liste.insert(10,"6-N° Carte Etudiant : " + self.maliste[5])
                self.liste.insert(11,"")
                self.liste.insert(12,"7-Site : " + self.maliste[6])
                self.liste.insert(13,"")
                self.liste.insert(14,"8-Résidence-Chambre : " + self.maliste[7])
                self.liste.insert(15,"")
                self.liste.insert(16,"9-Téléphone : " + self.maliste[8])
                self.liste.insert(17,"")
                self.liste.insert(18,"10-E-mail : " + self.maliste[9])
                self.liste.insert(19,"")
                self.liste.insert(20,"11-Ecole : " + self.maliste[10])
                self.liste.insert(21,"")
                self.liste.insert(22,"12-Filière : " + self.maliste[11])
                self.liste.insert(23,"")
                self.liste.insert(24,"13-Sexe : " + self.maliste[12])
                fichier.close()
                self.fen4.mainloop()
##------------------------------------------------------------------------------
    def modifier(self,event=None):
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        fichier.close()
        self.maliste=self.code[self.h].split("*²&~#@$§")
        self.fen4.destroy()
        self.fen3=Tk()
        self.fen3.resizable(0,0)
        self.fen3.title("Modification")
        self.fen3.config( relief=RAISED, bd=3,bg="light green")
        frameH = Frame(self.fen3, relief=GROOVE, bd=2,bg="orange")
        frameH.pack()
        frameH1=Frame(frameH, relief=GROOVE, bd=2,bg="cyan")
        frameH1.pack(side=LEFT)
        label=LabelFrame(frameH1,padx=10,pady=10,bg="cyan")
        label.pack(fill="both",expand="yes")
        label=LabelFrame(frameH1,text="Veuillez apporter vos différentes modifications !",font="Verdana 15 bold",padx=10,pady=10,bg="cyan")
        label.pack(fill="both",expand="yes")
        Label(label, text="Noms :",font="Verdana 15 bold",bg="cyan").grid( row=0, column=0, sticky=W,padx=10)
        self.nameEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.nameEnt.insert(1,self.maliste[0])
        self.nameEnt.grid( row=0, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Prénoms :",font="Verdana 15 bold",bg="cyan" ).grid( row=1, column=0, sticky=W,padx=10)
        self.prenameEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.prenameEnt.insert(1,self.maliste[1])
        self.prenameEnt.grid( row=1, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Date de naissance :",font="Verdana 15 bold",bg="cyan" ).grid( row=2, column=0, sticky=W,padx=10)
        self.dateEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.dateEnt.insert(1,self.maliste[2])
        self.dateEnt.grid( row=2, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Lieu de naissance :",font="Verdana 15 bold",bg="cyan" ).grid( row=3, column=0, sticky=W,padx=10)
        self.lieuEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.lieuEnt.insert(1,self.maliste[3])
        self.lieuEnt.grid( row=3, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="N° Carte Etudiant :",font="Verdana 15 bold",bg="cyan" ).grid( row=4, column=0, sticky=W,padx=10)
        self.carteEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.carteEnt.insert(1,self.maliste[5])
        self.carteEnt.grid( row=4, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Site :",font="Verdana 15 bold",bg="cyan" ).grid( row=5, column=0, sticky=W,padx=10)
        self.site=StringVar()
        self.site.set(self.maliste[6])
        option=OptionMenu(label,self.site,"INP CENTRE","   INP  SUD   ")
        option.grid(row=5, column=1, sticky=W, padx=20, pady=7,ipadx=129)
        Label(label, text="Résidence-Chambre :",font="Verdana 15 bold",bg="cyan" ).grid( row=6, column=0, sticky=W,padx=10)
        self.rchEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.rchEnt.insert(1,self.maliste[7])
        self.rchEnt.grid( row=6, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="N° Téléphone :",font="Verdana 15 bold",bg="cyan").grid( row=7, column=0, sticky=W,padx=10)
        self.phoneEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.phoneEnt.insert(1,self.maliste[8])
        self.phoneEnt.grid( row=7, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="E-mail :",font="Verdana 15 bold",bg="cyan" ).grid( row=8, column=0, sticky=W,padx=10)
        self.mailEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.mailEnt.insert(1,self.maliste[9])
        self.mailEnt.grid( row=8, column=1, sticky=W, padx=20, pady=7)
        Label(label, text="Ecole :",font="Verdana 15 bold",bg="cyan").grid( row=9, column=0, sticky=W,padx=10)
        self.ecole=StringVar()
        self.ecole.set(self.maliste[10])
        option=OptionMenu(label,self.ecole,"   ESI   ","   ESA  ","  ESTP "," ESMG","ESCAE","    EP   ")
        option.grid(row=9, column=1, sticky=W, padx=20, pady=7,ipadx=144)
        Label( label, text="Filière :",font="Verdana 15 bold",bg="cyan").grid( row=10, column=0, sticky=W,padx=10)
        self.filiereEnt = Entry(label,textvariable=str,width=40,font="TimesNewRoman 13 bold",relief=SUNKEN,borderwidth=3)
        self.filiereEnt.insert(1,self.maliste[11])
        self.filiereEnt.grid( row=10, column=1, sticky=W, padx=20, pady=7)
        Label(label,text="Sexe :",font="Verdana 15 bold",bg="cyan").grid( row=11, column=0, sticky=W,padx=10)
        self.sexe=StringVar()
        boutton1=Radiobutton(label,text="Masculin",font="TimesNewRoman 13 bold",bg="cyan",value="Masculin",variable=self.sexe)
        boutton1.grid( row=11, column=1, sticky=W, padx=20, pady=7)
        boutton2=Radiobutton(label,text="Féminin",font="TimesNewRoman 13 bold",bg="cyan",value="Féminin",variable=self.sexe)
        boutton2.grid( row=11, column=1, sticky=W, padx=130, pady=7)
        frameM = Frame(self.fen3,relief=GROOVE, bd=2,bg="red",padx=10,pady=5)
        frameM.pack()
        frameH2=Frame(frameH,bg="orange")
        frameH2.pack(side=RIGHT)
        photo = PhotoImage(file ='251180logo_inp.gif' )
        can1 = Canvas(frameH2, width =photo.width(), height =photo.height(),bg="orange")
        can1.create_image(0,0,anchor=NW,image =photo)
        can1.pack()
        frameB = Frame( self. fen3, relief=GROOVE, bd=3)
        frameB.pack(side=BOTTOM,pady=3)
        b1 = Button(frameB,text="Valider",underline=0,font="Verdana 12 bold",bg="orange",fg="black",padx=20,pady=5,command=self.valider)
        b2 = Button(frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="green",fg="black",padx=20,pady=5,command=self.retour2)
        b1.pack( side=LEFT, pady=2)
        b2.pack( side=LEFT, pady=2)
        self.fen3.mainloop()
##------------------------------------------------------------------------------
    def valider(self):
        a=self.nameEnt.get()
        b=self.prenameEnt.get()
        c=self.dateEnt.get()
        d=self.lieuEnt.get()
        f=self.carteEnt.get()
        g=self.site.get()
        h=self.rchEnt.get()
        l=self.phoneEnt.get()
        m=self.mailEnt.get()
        n=self.ecole.get()
        o=self.filiereEnt.get()
        q=self.sexe.get()
        if (a=="") or (b=="") or (c=="") or (d=="") or (f=="") or (g=="") or (h=="") or (l=="") or (m=="") or (n=="") or (o=="") or (a==" ") or (b==" ") or (c==" ") or (d==" ") or (f==" ") or (g==" ") or (h==" ") or (l==" ") or (m==" ") or (n==" ") or (o==" ") or (a=="Ex: AGBETOGOR") or (b=="Ex: KOKOU DZODZI GERMAIN") or (c=="Ex: 28-05-1997") or (d=="Ex: PORT-BOUET") or (f=="Ex: 14INP00631") or (h=="Ex: R-35") or (l=="Ex: 49 01 29 66") or (m=="Ex: agbegermain@gmail.com") or (o=="Ex: ING STIC1"):
            showwarning("Alerte","Veuillez renseigner les champs svp !!!")
            return
        elif q=="":
            showwarning("Alerte", "Veuillez sélectionner un sexe svp !!!")
            return
        f2=open("Germinator.txt", "r" )
        self.code=f2.readlines()
        f2.close()
        if askyesno("Question","Etes-vous sûr de vouloir modifier vos informations ?"):
            fichier=open("Germinator.txt","w")
            for i in range(len(self.code)):
                self.maliste=self.code[i].split("*²&~#@$§")
                if self.matricule==self.maliste[4]:
                    self.k=i
                    for j in range(len(self.code)):
                        if j!=self.k:
                            fichier.write("%s" % self.code[j])
                        if j==self.k:
                            fichier.write("%s\n" % (self.nameEnt.get()+"*²&~#@$§"+self.prenameEnt.get()+"*²&~#@$§"+self.dateEnt.get()+"*²&~#@$§"+self.lieuEnt.get()+"*²&~#@$§"+self.maliste[4]+"*²&~#@$§"+self.carteEnt.get()+"*²&~#@$§"+self.site.get()+"*²&~#@$§"+self.rchEnt.get()+"*²&~#@$§"+self.phoneEnt.get()+"*²&~#@$§"+self.mailEnt.get()+"*²&~#@$§"+self.ecole.get()+"*²&~#@$§"+self.filiereEnt.get()+"*²&~#@$§"+self.sexe.get()))
            self.maliste=self.code[self.h].split("*²&~#@$§")
            fichier.close()
            showinfo("Information","Modifiaction terminée !!!")
            self.fen3.destroy()
            self.fen4=Tk()
            self.fen4.resizable(0,0)
            self.fen4.title("Mes informations")
            self.fen4.config(bg="light green")
            frameH = Frame(self.fen4, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
            frameH.pack()
            label=LabelFrame(frameH,text="Voici vos différentes informations apportées comme modifications.",font="Verdana 15",bg="cyan")
            label.pack()
            photo = PhotoImage(file ='sablier,-chateau-de-sable-182334.gif' )
            can1 = Canvas(label, width =photo.width(), height =photo.height(),bg="cyan")
            can1.create_image(0,0,anchor=NW,image =photo)
            can1.pack(side=RIGHT)
            frameB = Frame(self.fen4, relief=GROOVE, bd=3)
            frameB.pack( pady=3)
            b1 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="orange",fg="black",command=self.retour5,padx=20,pady=5)
            b1.pack( side=LEFT, pady=2)
            b2 = Button( frameB,text="Supprimer",underline=0,font="Verdana 12 bold",bg="white",fg="black",command=self.supprimer,padx=20,pady=5)
            b2.pack( side=LEFT, pady=2)
            b3 = Button( frameB,text="Modifier",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.modifier,padx=20,pady=5)
            b3.pack( side=LEFT, pady=2)
            self.liste= Listbox(label,font="Castellar 13 bold",height=25,width=35)
            self.liste.pack(padx=5,pady=5,ipadx=5,ipady=5)
            self.liste.insert(0,"1-Noms : " + a)
            self.liste.insert(1,"")
            self.liste.insert(2,"2-Prénoms : " + b)
            self.liste.insert(3,"")
            self.liste.insert(4,"3-Date de naissance : " + c)
            self.liste.insert(5,"")
            self.liste.insert(6,"4-Lieu de naissance : " + d)
            self.liste.insert(7,"")
            self.liste.insert(8,"5-Mot de passe : " + self.maliste[4])
            self.liste.insert(9,"")
            self.liste.insert(10,"6-N° Carte Etudiant : " + f)
            self.liste.insert(11,"")
            self.liste.insert(12,"7-Site : " + g)
            self.liste.insert(13,"")
            self.liste.insert(14,"8-Résidence-Chambre : " + h)
            self.liste.insert(15,"")
            self.liste.insert(16,"9-Téléphone : " + l)
            self.liste.insert(17,"")
            self.liste.insert(18,"10-E-mail : " + m)
            self.liste.insert(19,"")
            self.liste.insert(20,"11-Ecole : " + n)
            self.liste.insert(21,"")
            self.liste.insert(22,"12-Filière : " + o)
            self.liste.insert(23,"")
            self.liste.insert(24,"13-Sexe : " + q)
            self.fen4.mainloop()
        else:
            showinfo("Information","Merci, aucune modification ne sera éffectuée !!!")
            self.fen3.destroy()
            self.fen4=Tk()
            self.fen4.resizable(0,0)
            self.fen4.title("Mes informations")
            self.fen4.config(bg="light green")
            frameH = Frame(self.fen4, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
            frameH.pack()
            label=LabelFrame(frameH,text="Vous pouvez en consultant vos informations de soit apporter une quelconque modification\nà vos données, soit de ne plus en faire partir en supprimant vos données.",font="Verdana 15",bg="cyan")
            label.pack()
            photo = PhotoImage(file ='sablier,-chateau-de-sable-182334.gif' )
            can1 = Canvas(label, width =photo.width(), height =photo.height(),bg="cyan")
            can1.create_image(0,0,anchor=NW,image =photo)
            can1.pack(side=RIGHT)
            frameB = Frame(self.fen4, relief=GROOVE, bd=3)
            frameB.pack( pady=3)
            b1 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="orange",fg="black",command=self.retour3,padx=20,pady=5)
            b1.pack( side=LEFT, pady=2)
            b2 = Button( frameB,text="Supprimer",underline=0,font="Verdana 12 bold",bg="white",fg="black",command=self.supprimer,padx=20,pady=5)
            b2.pack( side=LEFT, pady=2)
            b3 = Button( frameB,text="Modifier",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.modifier,padx=20,pady=5)
            b3.pack( side=LEFT, pady=2)
            self.liste= Listbox(label,font="Castellar 13 bold",height=25,width=35)
            self.liste.pack(padx=5,pady=5,ipadx=5,ipady=5)
            self.liste.insert(0,"1-Noms : " + self.maliste[0])
            self.liste.insert(1,"")
            self.liste.insert(2,"2-Prénoms : " + self.maliste[1])
            self.liste.insert(3,"")
            self.liste.insert(4,"3-Date de naissance : " + self.maliste[2])
            self.liste.insert(5,"")
            self.liste.insert(6,"4-Lieu de naissance : " + self.maliste[3])
            self.liste.insert(7,"")
            self.liste.insert(8,"5-Mot de passe : " + self.maliste[4])
            self.liste.insert(9,"")
            self.liste.insert(10,"6-N° Carte Etudiant : " + self.maliste[5])
            self.liste.insert(11,"")
            self.liste.insert(12,"7-Site : " + self.maliste[6])
            self.liste.insert(13,"")
            self.liste.insert(14,"8-Résidence-Chambre : " + self.maliste[7])
            self.liste.insert(15,"")
            self.liste.insert(16,"9-Téléphone : " + self.maliste[8])
            self.liste.insert(17,"")
            self.liste.insert(18,"10-E-mail : " + self.maliste[9])
            self.liste.insert(19,"")
            self.liste.insert(20,"11-Ecole : " + self.maliste[10])
            self.liste.insert(21,"")
            self.liste.insert(22,"12-Filière : " + self.maliste[11])
            self.liste.insert(23,"")
            self.liste.insert(24,"13-Sexe : " + self.maliste[12])
            self.fen4.mainloop()
##------------------------------------------------------------------------------
    def supprimer(self):
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        fichier.close()
        self.maliste=self.code[self.h].split("*²&~#@$§")
        if askyesno("Question","Etes-vous sûr de vouloir supprimer vos données ?"):
            fichier=open("Germinator.txt","w")
            for j in range(len(self.code)):
                if j!=self.h:
                    fichier.write("%s" % self.code[j])
                if j==self.h:
                    pass
            fichier.close()
            showinfo("Information","Suppression terminée !!!")
            self.fen4.destroy()
            self.fen2=Tk()
            self.fen2.resizable(0,0)
            self.fen2.title("Consultation")
            self.fen2.config(bg="light green")
            self.frameH = Frame(self.fen2, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
            self.frameH.pack()
            label=LabelFrame(self.frameH,text="Consulter la liste des inscris à ce service, vous donne l'autorisation de voir celle-ci et d'apporter ensuite différentes\nmodifications. Pour se faire cliquer sur le nom auquel vous voudriez apporter des modifications et suivez les instructions.",font="Verdana 15",bg="cyan")
            label.pack(pady=5)
            frameH1 = Frame(label,bg="cyan",padx=20,pady=20)
            frameH1.pack(side=LEFT)
            frameH2 = Frame(label,bg="cyan",padx=20,pady=20)
            frameH2.pack(side=RIGHT)
            frameB = Frame(self.fen2, relief=GROOVE, bd=3)
            frameB.pack( pady=3)
            b2 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.retour1,padx=20,pady=5)
            b2.pack( side=LEFT, pady=2)
            self.liste= Listbox(frameH1,font="Castellar 15 bold")
            sbar=Scrollbar(self.liste,orient=VERTICAL,command=self.liste.yview)
            self.liste.configure(yscrollcommand=sbar.set)
            sbar.pack(side=RIGHT,fill=Y)
            self.liste.pack(side=LEFT,expand=YES,fill=BOTH)
            photo=PhotoImage(file="intelligencia copie.gif")
            canvas=Canvas(frameH2,width=photo.width(),height=photo.height())
            canvas.create_image(0,0,anchor=NW,image=photo)
            canvas.pack()
            fichier=open("Germinator.txt","r")
            self.code=fichier.readlines()
            self.choix=StringVar()
            for i in range(len(self.code)):
                self.maliste=self.code[i].split("*²&~#@$§")
                boutton=Radiobutton(self.liste,text=self.maliste[0] + " " + self.maliste[1],variable=self.choix,value=self.maliste[0],font="Castellar 15 bold",command=self.afficher,bg="light green",fg="red")
                boutton.pack(side=TOP,ipady=10,ipadx=10,padx=5,pady=5,fill=BOTH)
            fichier.close()
            if len(self.code)==0:
                showinfo("Information","Le fichier des inscris à ce service est vide !!!")
            self.fen2.mainloop()
        else:
            showinfo("Information","Merci, aucune suppression ne sera éffectuée !!!")
##------------------------------------------------------------------------------
class Retour(Boutton):
# La classe Retour qui permet de faire les retours d'une fenetre a une autre.
##------------------------------------------------------------------------------
    def retour(self):
        self.fen1.destroy()
        Principale.__init__(self)
##------------------------------------------------------------------------------
    def retour1(self):
        self.fen2.destroy()
        Principale.__init__(self)
##------------------------------------------------------------------------------
    def retour2(self):
        self.fen3.destroy()
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        fichier.close()
        self.maliste=self.code[self.h].split("*²&~#@$§")
        self.fen4=Tk()
        self.fen4.resizable(0,0)
        self.fen4.title("Mes informations")
        self.fen4.config(bg="light green")
        frameH = Frame(self.fen4, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
        frameH.pack()
        label=LabelFrame(frameH,text="Vous pouvez en consultant vos informations de soit apporter une quelconque modification\nà vos données, soit de ne plus en faire partir en supprimant vos données.",font="Verdana 15",bg="cyan")
        label.pack()
        photo = PhotoImage(file ='sablier,-chateau-de-sable-182334.gif' )
        can1 = Canvas(label, width =photo.width(), height =photo.height(),bg="cyan")
        can1.create_image(0,0,anchor=NW,image =photo)
        can1.pack(side=RIGHT)
        frameB = Frame(self.fen4, relief=GROOVE, bd=3)
        frameB.pack( pady=3)
        b1 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="orange",fg="black",command=self.retour3,padx=20,pady=5)
        b1.pack( side=LEFT, pady=2)
        b2 = Button( frameB,text="Supprimer",underline=0,font="Verdana 12 bold",bg="white",fg="black",command=self.supprimer,padx=20,pady=5)
        b2.pack( side=LEFT, pady=2)
        b3 = Button( frameB,text="Modifier",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.modifier,padx=20,pady=5)
        b3.pack( side=LEFT, pady=2)
        self.liste= Listbox(label,font="Castellar 13 bold",height=25,width=35)
        self.liste.pack(padx=5,pady=5,ipadx=5,ipady=5)
        self.liste.insert(0,"1-Noms : " + self.maliste[0])
        self.liste.insert(1,"")
        self.liste.insert(2,"2-Prénoms : " + self.maliste[1])
        self.liste.insert(3,"")
        self.liste.insert(4,"3-Date de naissance : " + self.maliste[2])
        self.liste.insert(5,"")
        self.liste.insert(6,"4-Lieu de naissance : " + self.maliste[3])
        self.liste.insert(7,"")
        self.liste.insert(8,"5-Mot de passe : " + self.maliste[4])
        self.liste.insert(9,"")
        self.liste.insert(10,"6-N° Carte Etudiant : " + self.maliste[5])
        self.liste.insert(11,"")
        self.liste.insert(12,"7-Site : " + self.maliste[6])
        self.liste.insert(13,"")
        self.liste.insert(14,"8-Résidence-Chambre : " + self.maliste[7])
        self.liste.insert(15,"")
        self.liste.insert(16,"9-Téléphone : " + self.maliste[8])
        self.liste.insert(17,"")
        self.liste.insert(18,"10-E-mail : " + self.maliste[9])
        self.liste.insert(19,"")
        self.liste.insert(20,"11-Ecole : " + self.maliste[10])
        self.liste.insert(21,"")
        self.liste.insert(22,"12-Filière : " + self.maliste[11])
        self.liste.insert(23,"")
        self.liste.insert(24,"13-Sexe : " + self.maliste[12])
        self.fen4.mainloop()
##------------------------------------------------------------------------------
    def retour3(self):
        self.fen4.destroy()
        self.fen2=Tk()
        self.fen2.resizable(0,0)
        self.fen2.title("Consultation")
        self.fen2.config(bg="light green")
        self.frameH = Frame(self.fen2, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
        self.frameH.pack()
        label=LabelFrame(self.frameH,text="Consulter la liste des inscris à ce service, vous donne l'autorisation de voir celle-ci et d'apporter ensuite différentes\nmodifications. Pour se faire cliquer sur le nom auquel vous voudriez apporter des modifications et suivez les instructions.",font="Verdana 15",bg="cyan")
        label.pack(pady=5)
        frameH1 = Frame(label,bg="cyan",padx=20,pady=20)
        frameH1.pack(side=LEFT)
        frameH2 = Frame(label,bg="cyan",padx=20,pady=20)
        frameH2.pack(side=RIGHT)
        frameB = Frame(self.fen2, relief=GROOVE, bd=3)
        frameB.pack( pady=3)
        b2 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.retour1,padx=20,pady=5)
        b2.pack( side=LEFT, pady=2)
        self.liste= Listbox(frameH1,font="Castellar 15 bold")
        sbar=Scrollbar(self.liste,orient=VERTICAL,command=self.liste.yview)
        self.liste.configure(yscrollcommand=sbar.set)
        sbar.pack(side=RIGHT,fill=Y)
        self.liste.pack(side=LEFT,expand=YES,fill=BOTH)
        photo=PhotoImage(file="intelligencia copie.gif")
        canvas=Canvas(frameH2,width=photo.width(),height=photo.height())
        canvas.create_image(0,0,anchor=NW,image=photo)
        canvas.pack()
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        self.choix=StringVar()
        for i in range(len(self.code)):
            self.maliste=self.code[i].split("*²&~#@$§")
            boutton=Radiobutton(self.liste,text=self.maliste[0] + " " + self.maliste[1],variable=self.choix,value=self.maliste[0],font="Castellar 15 bold",command=self.afficher,bg="light green",fg="red")
            boutton.pack(side=TOP,ipady=10,ipadx=10,padx=5,pady=5,fill=BOTH)
        fichier.close()
        if len(self.code)==0:
            showinfo("Information","Le fichier des inscris à ce service est vide !!!")
        self.fen2.mainloop()
##------------------------------------------------------------------------------
    def retour4(self):
        self.fen5.destroy()
        Principale.__init__(self)
##------------------------------------------------------------------------------
    def retour5(self):
        self.fen4.destroy()
        self.fen6=Tk()
        self.fen6.resizable(0,0)
        self.fen6.title("Consultation")
        self.fen6.config(bg="light green")
        self.frameH = Frame(self.fen6, relief=GROOVE, bd=2,bg="cyan",padx=20,pady=20)
        self.frameH.pack()
        label=LabelFrame(self.frameH,text="Consulter la liste des inscris à ce service, vous donne l'autorisation de voir celle-ci et d'apporter ensuite différentes\nmodifications. Pour se faire cliquer sur le nom auquel vous voudriez apporter des modifications et suivez les instructions.",font="Verdana 15",bg="cyan")
        label.pack(pady=5)
        frameH1 = Frame(label,bg="cyan",padx=20,pady=20)
        frameH1.pack(side=LEFT)
        frameH2 = Frame(label,bg="cyan",padx=20,pady=20)
        frameH2.pack(side=RIGHT)
        frameB = Frame(self.fen6, relief=GROOVE, bd=3)
        frameB.pack( pady=3)
        b2 = Button( frameB,text="Retour",underline=0,font="Verdana 12 bold",bg="green",fg="black",command=self.retour6,padx=20,pady=5)
        b2.pack( side=LEFT, pady=2)
        self.liste= Listbox(frameH1,font="Castellar 15 bold")
        sbar=Scrollbar(self.liste,orient=VERTICAL,command=self.liste.yview)
        self.liste.configure(yscrollcommand=sbar.set)
        sbar.pack(side=RIGHT,fill=Y)
        self.liste.pack(side=LEFT,expand=YES,fill=BOTH)
        photo=PhotoImage(file="intelligencia copie.gif")
        canvas=Canvas(frameH2,width=photo.width(),height=photo.height())
        canvas.create_image(0,0,anchor=NW,image=photo)
        canvas.pack()
        fichier=open("Germinator.txt","r")
        self.code=fichier.readlines()
        self.choix=StringVar()
        for i in range(len(self.code)):
            self.maliste=self.code[i].split("*²&~#@$§")
            boutton=Radiobutton(self.liste,text=self.maliste[0] + " " + self.maliste[1],variable=self.choix,value=self.maliste[0],font="Castellar 15 bold",command=self.afficher1,bg="light green",fg="red")
            boutton.pack(side=TOP,ipady=10,ipadx=10,padx=5,pady=5,fill=BOTH)
        fichier.close()
        if len(self.code)==0:
            showinfo("Information","Le fichier des inscris à ce service est vide !!!")
        self.fen6.mainloop()
##------------------------------------------------------------------------------
    def retour6(self):
        self.fen6.destroy()
        Principale.__init__(self)
##------------------------------------------------------------------------------
class Lancement(Retour):
#La classe Lancement qui permet d'ouvrir la fenetre principale et qui fait appel a toutes les autres classes.
##------------------------------------------------------------------------------
    def __init__(self):
        Principale.__init__(self)
##------------------------------------------------------------------------------
app = Lancement()
# Lancement du programme permettant d'executer toutes les classes definies ci-dessus.
##------------------------------------------------------------------------------